// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmlyjgqbzjuhqeegneth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbHlqZ3Fiemp1aHFlZWduZXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzI0NzMsImV4cCI6MjA2MTAwODQ3M30.lZZ2mSlvIpvZFvc49ZypBQvLkpG_bzs4YLW2zDUx0VI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);